#!/bin/bash
#PBS -q workq
#PBS -l nodes=1:ppn=20
#PBS -l walltime=3:00:00
#PBS -N pasta   
#PBS -o raxml_pasta.out
#PBS -j oe
#PBS -A loni_selu_sys
#PBS -m abe
#PBS -M april.wright@selu.edu   


module load java
module load python/3.5.2-anaconda-tensorflow
cd  /work/amwright/lab1

python ~/pasta/run_pasta.py -i data/small.fasta --tree-estimator=raxml -j smallrax
